language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install:
  - cd newman-assert && ./build.sh

addons:
  sonarqube:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

script:
  - mvn install sonar:sonar -P run-its

branches:
  only:
    - master
