language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install:
  - cd newman-assert && ./build.sh && cd ..

addons:
  sonarcloud:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

script:
  - mvn install sonar:sonar -P run-its

after_failure:
  - cat target/it/interpolated-settings.xml
  - cat target/it/simple-it/build.log
  - cat target/it/simple-it/target/*.{result,json}

branches:
  only:
    - master
