language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

addons:
  sonarqube:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

branches:
  only:
    - master
